// <auto-generated />
using C2E.Api.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace C2E.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417000000_AddUserDisplayName")]
    partial class AddUserDisplayName
    {
    }
}
